### ISSUE TITLE
Can't make multiple lists

### ISSUE THREAD

**Issue by MathiasSvDK** [whyvra/Whyvra.Blazor.Forms#1] opened 2021-06-28 15:50 UTC
When i make 2 Lists in a single modal it makes it a single radio box.

See attachted.
![image](https://user-images.githubusercontent.com/45672692/123666307-625e1300-d839-11eb-86aa-029db4939711.png)

If i select for example "DKK" my option from selected "Month" will be removed and it will instead be "DKK".

**Comment by whyvra** [comment] 2021-07-05 16:47
Do you have some code to reproduce this? What's your FormBuilder and data model looking like?

**Comment by whyvra** [comment] 2021-08-13 11:50
I have tried adding two lists on a form and it seems to work just fine.

![Whyvra Blazor Forms_Lists](https://user-images.githubusercontent.com/24640090/129352889-dcbd3bef-59a0-4ce0-af93-f14848457a18.PNG)

Without more info, it's almost impossible to say what could be the cause of this issue for you. As per your screenshot, it does look like you're using a custom renderer so it could be a logic error there.

I will close this issue for now.

**Closed as completed by whyvra** 2021-08-13 11:50 UTC
Labels: need more info
